services:
  server:
    # Build the image from the Dockerfile in the server directory
    build: ./server
    ports:
      # Map the container port 8080 to the host port 8080
      - "8080:8080"
    # Mount the server code to the container for live reloading during development
    volumes:
      - ./server:/app

  client:
    # Build the image from the Dockerfile in the client directory
    build: ./client
    ports:
      # Map the container port 5173 to the host port 5173
      - "5173:5173"
    # Mount the client code for live reloading
    volumes:
      - ./client:/app
    # Set up a dependency to ensure the server starts first
    depends_on:
      - server