services:
  server:
    build: ./server
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=prod

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - server
